/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fdvearwstzqlplcpxouu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkdmVhcndzdHpxbHBsY3B4b3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNTQ4MzIsImV4cCI6MjA5NTYzMDgzMn0.rc-ZH-DXmwer7XOAXG8Fcj0NRRHL9N1CHiCKZ1UhbcI"