// One-time generator. Run with:
//   npx tsx data_migration/generateFullV2Library.ts > src/data/v2/exercises.full.ts
//
// Produces a fully static v2 exercise array covering all 422 v1 exercises
// (via the adapter) PLUS the 77 hand-curated ones from the original seed —
// hand-curated entries win on id collision (they don't collide today since
// they use different id schemes, but this keeps the merge safe if that
// ever changes). Output is plain TypeScript data, not a runtime import of
// v1 — this is the actual decoupling step: once this file replaces
// src/data/v2/exercises.ts, v2 no longer needs src/data/exercises.ts to
// exist at all.
//
// This does NOT fix the adapter's documented precision loss (side-delts,
// coarse equipment mapping, movementId-only substitution groups for the
// adapted 422) — it just makes that already-known tradeoff permanent
// static data instead of a runtime bridge. See adaptV1ToV2.ts for what's
// lost and why.

import { exerciseDatabase as v1db } from '../src/data/exercises';
import { exerciseDatabase as curatedV2 } from '../src/data/v2/exercises.curated';
import { adaptV1Database } from '../src/utils/adaptV1ToV2';
import { checkIntegrity } from '../src/data/v2/integrityCheck';

const adapted = adaptV1Database(v1db);
const curatedIds = new Set(curatedV2.map((e) => e.id));
const adaptedDeduped = adapted.filter((e) => !curatedIds.has(e.id));

const merged = [...curatedV2, ...adaptedDeduped];

const issues = checkIntegrity(merged);
const singletonWarnings = issues.filter((i) => i.problem.includes('no swap candidates'));
const hardErrors = issues.filter((i) => !i.problem.includes('no swap candidates'));

console.error(`// Generated ${new Date().toISOString()}`);
console.error(`// ${curatedV2.length} curated + ${adaptedDeduped.length} adapted (${adapted.length - adaptedDeduped.length} deduped) = ${merged.length} total`);
console.error(`// Integrity: ${hardErrors.length} hard error(s), ${singletonWarnings.length} singleton-substitution-group warning(s)`);
if (hardErrors.length > 0) {
  console.error('HARD ERRORS — fix before using this output:');
  for (const e of hardErrors) console.error(`  [${e.exerciseId}] ${e.problem}`);
  process.exit(1);
}

console.log(`import type { Exercise } from './types';

// ─── Full V2 exercise library ──────────────────────────────────────────────
// Generated by data_migration/generateFullV2Library.ts — do not hand-edit
// individual adapted entries here; fix the source (adaptV1ToV2.ts mapping
// tables, or src/data/exercises.ts) and regenerate instead, or this file
// will drift from its source of truth on the next regeneration.
//
// ${curatedV2.length} exercises are hand-curated (rich attributes, curated
// cross-movement substitution groups) — these came from the original v2
// seed set and are unchanged here.
// ${adaptedDeduped.length} exercises are adapted from the v1 database.
// Known precision loss on adapted entries (see adaptV1ToV2.ts for detail):
//   - "shoulders" always maps to front-delts only (v1 has no delt-head
//     distinction) — side-delts and rear-delts volume can be undercredited
//     for adapted entries.
//   - equipmentNeeded is a single representative item per equipmentType,
//     not the true granular equipment list (v1 doesn't track that).
//   - substitutionGroupId falls back to movementId (same-movement
//     equipment variants only) rather than the curated cross-movement
//     groups the hand-authored 77 exercises have.

export const exerciseDatabase: Exercise[] = ${JSON.stringify(merged, null, 2)};
`);
